// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqserfbmpcbeqxixjeic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxc2VyZmJtcGNiZXF4aXhqZWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NTgxOTEsImV4cCI6MjA3NjMzNDE5MX0.GK53scRDwGr5GAB1JNKnX4lFMhL8ixHcpoDjAVsx2gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});